[functions]
  external_node_modules = [
    "express",
    "serverless-http",
    "dotenv",
    "path",
    "body-parser",
    "googleapis"
  ]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
